### ISSUE TITLE
[BUG] `yarn dpdm --no-warning --no-tree ./src/**/*` producing inconsistent output

### ISSUE THREAD

**Issue by alexwnoseworthy** [acrazing/dpdm#34]
**Describe the bug**
- On every commit we run  `yarn dpdm --no-warning --no-tree ./src/**/* > circularDependencies.txt` 
- For some of the developers working on the project this is producing an inconsistent output, toggling the circularDependencies.txt file between two states, one being the correct output and the other is incorrect containing about 1/3rd of the content that it should. 
- We've been able to identify one difference when running the command between developers who have the issue and those who do not
  - Those who don't have the issue will get this message after running the command `✔ [997/997] Analyze done!`
  - Those who do have the issue will have a value of 1 lower for in the message  `✔ [996/996] Analyze done!`. 

**To Reproduce**
1. Run `yarn dpdm --no-warning --no-tree ./src/**/* > circularDependencies.txt`
2. This will occasionally result in the circularDependencies.txt changing even if there have been 0 changes since the last time the command was run
3.  Run `yarn dpdm --no-warning --no-tree ./src/**/* > circularDependencies.txt` again and it will changing back to it's previous state
4. Note: Sometimes this happens every time the command is run and sometimes it only happens every ~5 or so times

**Expected behaviour**
- We expect a consistent output in the `circularDependencies.txt` file that is accurate

**Screenshots**
Here is an example of the file being toggled on back to back empty commits.
![Screenshot 2023-06-01 at 5 53 26 PM](https://github.com/acrazing/dpdm/assets/112956663/a20ea12b-421f-490d-8334-c2de97f4685a)

**Comment by acrazing** [comment]
I speculate that the reason for the problematic version is because the `src` directory at that time contained some files that were ignored by `.gitignore`, such as compiled results.

You can try to add an option `-o some_file.json` to print the full state. Then compare the problematic version with the version that doesn't have any issues, and see what differences exist in their content. In your case, you only need to compare the entries inside. By identifying the additional file in the problematic version, you can analyze the reason behind it.

The full command for you could be:

```bash
yarn dpdm --no-warning --no-tree ./src/**/* -o test.json > circularDependencies.txt
```

Then compare the `test.json`:

```bash
diff <(jq -r '.entries | sort | .[]' ok_test.json) <(jq -r '.entries | sort | .[]' fail_test.json)
```

Alternatively, could you share the content of circularDependencies.txt? Perhaps I can find some clues in it.

**Comment by alexwnoseworthy** [comment]
@acrazing thanks for the tip, I'll doing some comparison next week using your recommendation and I'll post my results here.
