### ISSUE TITLE
Are there aliases support?

### ISSUE THREAD

**Issue by zarabotaet** [acrazing/dpdm#5]

**Comment by acrazing** [comment]
Yes, it supports TypeScript [path mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) now. It uses `tsconfig.json` in your context directory if it exists, and you can pass `--tsconfig FILENAME` to specify custom ts json config file.

Please note that it does not currently support webpack aliases.

**Comment by yairEO** [comment]
Hi, the README is unclear for the `tsconfig` setting, if it automatically tries to use `jsconfig` also

![image](https://user-images.githubusercontent.com/845031/180779412-ffa9c407-0a2c-4f02-80f2-877f0bca3515.png)
 
That isn't mentioned anywhere, and `jsconfig` filename is more common than `tscnofig` (because _typescript_ it not a real language and is not the norm).
 
I've tried running `dpdm` with the `tsconfig` flag pointing to my `jsconfig.json` file  (located on the project's root folder) but I don't think it is working:

    dpdm src\foo.jsx --tsconfig jsconfig.json
